source "https://gems.ruby-china.com" # gems.ruby-china.com rubygems.org

gem "jekyll-rtd-theme"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
 gem 'jekyll-commonmark'
gem 'jekyll-slim'
gem 'slim', github: 'slim-template/slim'
gem 'jekyll-textile-converter'
   gem "premonition", "4.0.1"
gem "jekyll-github-metadata"
